
spring:
  thymeleaf:
    cache: false #  关闭thymeleaf模版缓存
  datasource:
    url: jdbc:mysql://localhost:3306/seckill?allowPublicKeyRetrieval=true&useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root123456
    hikari: # springboot自带的数据库链接池,号称最快的链接池
      pool-name: DateHikariCP # 链接池名字
      minimum-idle: 5 # 最小空闲链接数
      idle-timeout: 180000 # 空闲链接存活最大时间，默认600000（10 分钟）
      maximum-pool-size: 10 # 最大链接数 默认 10
      auto-commit: true # 自动提交 （从连接池返回的链接自动提交）
      max-lifetime: 180000 # 链接最大存活时间，0表示永久，默认1800000（30分钟）
      connection-timeout: 30000 # 链接超时时间 默认30秒
      connection-test-query: SELECT 1 # 心跳机制（测试连接是否可用的查询语句）
  redis: # redis配置
    host: localhost
    port: 6379
    database: 0
    timeout: 10000ms # 超时时间
    password: redis
    lettuce: # 连接池配置
      pool:
        max-active: 8 # 最大连接数 默认8
        max-wait: 10000ms # 最大的连接阻塞等待时间
        max-idle: 200 # 最大空闲连接数
        min-idle: 8 # 最小空闲连接数
  rabbitmq:
    host: localhost # rabbitmq主机
    port: 5672 # rabbitmq主机端口
    username: guest # rabbitmq用户名 默认是guest
    password: guest # rabbitmq密码 默认是guest
    virtual-host: / # 虚拟主机 /guest
    listener:
      simple:
        concurrency: 10 # 消费者最小数量
        max-concurrency: 10 # 消费者最大数量
        prefetch: 1 # 限制消费者每次只处理一条数据，处理完成后在处理下一条数据
        auto-startup: true # 启动时是否默认启动容器
        default-requeue-rejected: true # 被拒接时重新回到队列中
    template:
      retry:
        enabled: true # 发布重试,默认false
        initial-interval: 1000ms # 重试时间 默认1000ms
        max-attempts: 3 # 重试最大次数 默认3
        max-interval: 10000ms # 重试最大时间 默认10000ms
        multiplier: 1 # 重试的间隔层数 , 比如配置的是 2 第一次重试等待时间为 10s 第二次等待时间为 20s 第三次等待时间为 40s


mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml # 配置Mapper.xml映射文件
  type-aliases-package: com.yang.seckill.pojo # 配置mybatisPlus数据返回的类型别名，（默认，别名就是类名）
# 日志配置
logging:
  level:
    com.yang.seckilldemo.mapper: debug
server:
  port: 8091